version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "6-SofuriHafe"
      - match:
          dependency_name: "6-smmac72"
      - match:
          dependency_name: "6-SlavaLatokhin"
      - match:
          dependency_name: "6-ShishaK1N9"
      - match:
          dependency_name: "6-rudolf101"
      - match:
          dependency_name: "6-Ramazanov-Amir"
      - match:
          dependency_name: "6-qsqnk"
      - match:
          dependency_name: "6-PyRayman"
      - match:
          dependency_name: "6-pervomai"
      - match:
          dependency_name: "6-Naniduan"
      - match:
          dependency_name: "6-Mishavint"
      - match:
          dependency_name: "6-michael555444"
      - match:
          dependency_name: "6-MDubovik"
      - match:
          dependency_name: "6-Lev0nid"
      - match:
          dependency_name: "6-kettlberry"
      - match:
          dependency_name: "6-IraSheremet"
      - match:
          dependency_name: "6-IlyaMuravjov"
      - match:
          dependency_name: "6-IAmFunkyFrog"
      - match:
          dependency_name: "6-foreverjun"
      - match:
          dependency_name: "6-fertmanasa"
      - match:
          dependency_name: "6-esvault"
      - match:
          dependency_name: "6-danielsheh02"
      - match:
          dependency_name: "6-AzimMuradov"
      - match:
          dependency_name: "6-AShlegel"
      - match:
          dependency_name: "6-artmotika"
      - match:
          dependency_name: "6-AndreyBryns"
    ignored_updates:
      - match:
          dependency_name: "6-grading-tests"
